# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 03:21
from __future__ import unicode_literals

import api.invite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(null=True)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], max_length=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.NullBooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField(default=api.invite.models.Invite.get_expiration)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('home_phone', models.CharField(max_length=10, null=True)),
                ('cell_phone', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], max_length=1)),
                ('dob', models.DateField(null=True)),
                ('dogs', models.ManyToManyField(to='api.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dog',
            name='humans',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
