# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
