# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
