# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='properties',
            field=models.ManyToManyField(null=True, to='api.RoomProperty'),
        ),
    ]
