# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:34
from __future__ import unicode_literals

import api.models.invite
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_dog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.NullBooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField(default=api.models.invite.Invite.get_expiration)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
