# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='dog',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Dog'),
            preserve_default=False,
        ),
    ]
