# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invite_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='dog',
        ),
        migrations.AddField(
            model_name='invite',
            name='dogs',
            field=models.ManyToManyField(to='api.Dog'),
        ),
    ]
